apiVersion: v1
kind: Secret
metadata:
  name: easyshop-secrets
  namespace: easyshop
type: Opaque
stringData:
  JWT_SECRET: +SGzN/+uINXri14Qf9itSwL/U39OG+q+BN2STl4EDe8=
  NEXTAUTH_SECRET: Nm36vYXuj+F+qLii33tq3I0PI5L9L0Yq3XvWmo2i/Vk=
